[build]
  # Build command for the React app
  command = "npm install --legacy-peer-deps --force && vite build"
  # Publish directory (Vite build output)
  publish = "dist"
  # Functions directory for serverless API
  functions = "netlify/functions"

# Secrets scanning configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18.19.0"
  BACKUP_MAX_ROWS = "100000"
  # Disable secrets scanning for expected files
  SECRETS_SCAN_ENABLED = "false"

# API redirects to serverless functions - MUST COME FIRST
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Health check redirect
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200
  force = true

# Test environment redirect
[[redirects]]
  from = "/test-env"
  to = "/.netlify/functions/api/test-env"
  status = 200
  force = true

# SPA routing - MUST COME LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-api-key, x-app-version, x-env, x-admin-email"
